#!/usr/bin/env bash
# Sync ~/.ai/*.md global agent policies into ./.cursor/rules/*.mdc.
#
# Source of truth: ~/.ai/*.md (also imported by ~/.claude/CLAUDE.md).
# Re-run this script whenever those source files change.
#
# Each generated .mdc file gets `alwaysApply: true` frontmatter so Cursor
# applies the rule to every chat in this project, matching the way
# Claude Code loads ~/.ai/*.md globally.

set -euo pipefail

SOURCE_DIR="${HOME}/.ai"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_DIR="${PROJECT_ROOT}/.cursor/rules"

if [[ ! -d "${SOURCE_DIR}" ]]; then
  echo "error: source dir not found: ${SOURCE_DIR}" >&2
  exit 1
fi

mkdir -p "${TARGET_DIR}"

shopt -s nullglob
count=0
for src in "${SOURCE_DIR}"/*.md; do
  name="$(basename "${src}" .md)"
  dest="${TARGET_DIR}/${name}.mdc"

  {
    printf -- '---\n'
    printf 'description: %s\n' "Mirror of ~/.ai/${name}.md (generated by scripts/sync-cursor-rules.sh)"
    printf 'alwaysApply: true\n'
    printf -- '---\n\n'
    cat "${src}"
  } > "${dest}"

  echo "synced: ${dest#${PROJECT_ROOT}/}"
  count=$((count + 1))
done

if [[ "${count}" -eq 0 ]]; then
  echo "warning: no *.md files found in ${SOURCE_DIR}" >&2
fi

echo "done (${count} file(s))"
